### ISSUE TITLE
`/zabo/boards` API 추가

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/zabo-server-nodejs#140]
# Summary 

Suggested by @jinho-choi123, @SnowSuno 

해결할 사항은 아래와 같습니다 ([10/29 회의록(로그인 필요)](https://www.notion.so/sparcs/10-27-8f70e6606f28443db3a85d55a6767f9a?pvs=4#474a3fce5930426587674ba0fa07777b)에서 가져왔습니다).

1. Zabo Boards 기기에서 보내진 요청이 맞는지 검증할 필요가 있음
    1. 프론트엔드에서는 서비스 시작 시 `deviceId`를 입력해 state로 저장합니다.
    2. 프론트엔드에서 `/zabo/board` API 요청 시 `deviceId`를 (쿠키에) 포함하고, 백엔드에서는 `deviceId` 바탕으로 요청을 검증한 뒤 기기별 보여진 자보를 집계합니다.
2. 이벤트 집계의 경우 기존 `statisticsModel`을 사용할 수 있지만, 이 모델은 user-zabo의 1:1 관계이므로 user가 필요합니다.

# Tasks 

- [x] `deviceId`를 DB에 추가하는 기능
- [x] `/zabo/board` API 작성
	- [x] `deviceId`를 바탕으로 `statisticsModel`에 오프라인 자보 조회 통계를 추가하기

**Comment by jinho-choi123** [comment]
Device을 statisticsModel에 넣는게 좋을지 다시한번 더 고민해보면 좋을것 같습니다. 지금 저희의 statisticModel은 user관련된 event을 로깅하고 있습니다. 그런데 여기에 device statistics 관련 로그도 넣는게 맞을까요...?
